import time

print()
print('Como castigan a los niños del teleton?')
input()
print('¡Los desarman!')
print()
time.sleep(2)
print('Porque vuelan los pajaros pa\'l sur?')
input()
print('¡Porque caminando tardarían muchísimo!')
print()
time.sleep(2)
print('¿En qué se parecen una familia, un bombero y un barco?')
input()
print("No sé... ¿en qué se parecen?")
input()
print('En que el bombero y el barco tienen casco.')
input()
print('Y la familia?', end='')
print('-Bien, gracias.')
